image: Visual Studio 2017

#Publish to PowerShell Gallery with this key
environment:
  NugetApiKey:
    secure: 76Y+lNAkDCWwiO9jWmihZBlOKPD2rtU3b+dd5Fpkz34WtXFqTKDQFp30IA60Cj3e
  CODECOV_TOKEN:
    secure: xn88TAvqQYjOWy5VnVNLLDNIeYi75NcrDMZdcEoAFPpW91KcdPSwk4NnvUxLI9hG
  PSDPA_BASEURI:
    secure: /Ah4/9vQOkXmMZdB8SrlHqueDF5uMC/ME3pc8jgl7qqiR1rpG+W3mjyeR+FbxOPh
  PSDPA_TOKEN:
    secure: kTA548nZiwq71GIiCau5wvSPTVNn9dVfaHC//NuCKo2fljzkpL+niUwjfOVvVIbDPf8zOxznxspn1GrEkm27Dg8XGHyd9XfD8leyiKTp0gavhNLVkrVzG1/Zqj6eyFO7IKVGYB4hs7nJJasuAFxVtBjcR9UZdFEbw8d/Z06YqQo=
  PSDPA_AZ:
    secure: 3vZUMa+iGf9aqcTolqBjG+tkPnbe3HIzVMBVJkW4dVTqi8t36MmPeXuMcKefJsXe
  PSDPA_AZ_TENANT: 1e220ef3-d984-4f20-9bc7-a54afa8ec2af
  PSDPA_AZ_APP: 66fb92de-ce0b-48cd-8839-d70991013dd8

cache:
  - C:\Users\appveyor\Documents\WindowsPowerShell\Modules -> Build\build.requirements.psd1

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build\Start-Build.ps1 -Task Deploy